from ..constants import PIPE

class PIPELINE:

    GET_USERS = [
        PIPE.DATA.USERS.GET_WAREHOUSE_NAME,
        PIPE.DATA.USERS.GET_JOB_NAME,
        PIPE.PROCESSING.ASSIGN_DTYPES,
    ]

    GET_RECORDS = [
        PIPE.PROCESSING.GET_USER_NAMES,
        PIPE.PROCESSING.ASSIGN_DTYPES,
        PIPE.PROCESSING.RECORDS.ADD_DATE_AND_TIME,
        PIPE.PROCESSING.ASSIGN_DTYPES, 
        PIPE.COLUMNS_SELECTION.ASSISTANCE_RECORDS,
    ]

    GET_CORRECTIONS = [
        PIPE.PROCESSING.GET_USER_NAMES,
        PIPE.PROCESSING.TIME_FIRST_TO_STRING,
        PIPE.PROCESSING.NULL_BY_JUSTIFICATION,
        PIPE.PROCESSING.ASSIGN_DTYPES,
        PIPE.PROCESSING.ASSIGN_ORDERED_REGISTRY_TYPE,
        PIPE.PROCESSING.ADD_REGISTRY_TIME,
        PIPE.PROCESSING.ASSIGN_DTYPES,
        PIPE.DATA.CORRECTIONS.ADD_CORRECTION_TAG,
        PIPE.DATA.CORRECTIONS.SORT_BY_DATE,
        PIPE.COLUMNS_SELECTION.CORRECTIONS,
    ]

    GET_JUSTIFICATIONS = [
        PIPE.DATA.JUSTIFICATIONS.RENAME_COLUMNS,
        PIPE.PROCESSING.JUSTIFICATIONS.GET_AND_KEEP_BY_USER_ID,
        PIPE.PROCESSING.JUSTIFICATIONS.FORMAT_PERMISSION_DATE_STRINGS,
        PIPE.PROCESSING.ASSIGN_DTYPES,
        PIPE.COLUMNS_SELECTION.JUSTIFICATIONS,
    ]

    UPDATE_DATABASE = [
        PIPE.PROCESSING.RECORDS.PROCESS_BEFORE_SAVE_IN_DATABASE,
        PIPE.PROCESSING.ASSIGN_DTYPES,
        PIPE.COLUMNS_SELECTION.ASSISTANCE_RECORDS_UPDATE,
    ]

    CORRECT_RECORDS = [
        PIPE.PROCESSING.RECORDS.DISCARD_DUPLICATED,
        PIPE.PROCESSING.RECORDS.DISCARD_CORRECTED_RECORDS,
        PIPE.PROCESSING.RECORDS.CONCAT_CORRECTIONS,
        PIPE.PROCESSING.ASSIGN_DTYPES,
        PIPE.PROCESSING.RECORDS.ASSIGN_DAY_AND_USER_INDEX,
    ]

    VALIDATE_RECORDS = [
        PIPE.PROCESSING.RECORDS.PIVOTED.COUNT_PER_REGISTRY_TYPE,
        PIPE.PROCESSING.RECORDS.PIVOTED.VALIDATE_RECORDS,
        PIPE.COLUMNS_SELECTION.PIVOTED.RECORDS,
    ]

    VALIDATE_TODAY_CHECKIN = [
        PIPE.PROCESSING.RECORDS.VALIDATE_TODAY_CHECKIN,
        PIPE.PROCESSING.ASSIGN_DTYPES,
        PIPE.COLUMNS_SELECTION.VALIDATE_TODAY_CHECKIN,
    ]

    EVALUATE_REGISTRY_TIMES = [
        PIPE.PROCESSING.RECORDS.GET_DAILY_SCHEDULES,
        PIPE.PROCESSING.RECORDS.GET_SCHEDULE_OFFSETS,
        PIPE.PROCESSING.RECORDS.ALLOWED_START_AND_END,
        PIPE.PROCESSING.RECORDS.GET_CUMMULATED_TIME,
        PIPE.COLUMNS_SELECTION.EVALUATE_REGISTRY_TIMES,
    ]
