from ..constants import PIPE_VALIDATION_ERROR_MESSAGE_ARGS

class PIPE_VALIDATION_ERROR_MESSAGE:
    """
    `Literal` Mensajes de error.
    """
    REQUIRE = f'Las columnas {{{PIPE_VALIDATION_ERROR_MESSAGE_ARGS.MISSING_COLUMNS}}} no existen para {{{PIPE_VALIDATION_ERROR_MESSAGE_ARGS.PIPE_NAME}}}'
    RENAME = f'Las columnas {{{PIPE_VALIDATION_ERROR_MESSAGE_ARGS.MISSING_COLUMNS}}} a renombrar no existen para {{{PIPE_VALIDATION_ERROR_MESSAGE_ARGS.PIPE_NAME}}}'
    SELECT = f'Las columnas {{{PIPE_VALIDATION_ERROR_MESSAGE_ARGS.MISSING_COLUMNS}}} a seleccionar no existen para {{{PIPE_VALIDATION_ERROR_MESSAGE_ARGS.PIPE_NAME}}}'
