from pandas._typing import AstypeArg
from .._constants import (
    COLUMN,
    PERMISSION_NAME,
    REGISTRY_TYPE,
    WAREHOUSE_NAME,
)
from .._settings import INPUT, DATA

ASSIGNED_DTYPES: dict[str, AstypeArg] = {
    COLUMN.ID: 'string[python]',
    COLUMN.USER_ID: 'uint16',
    COLUMN.NAME: 'category',
    COLUMN.DATE: 'datetime64[s]',
    COLUMN.TIME: 'timedelta64[ns]',
    COLUMN.REGISTRY_TYPE: 'category',
    COLUMN.DEVICE: 'category',
    COLUMN.PAY_FREQUENCY: 'category',
    COLUMN.IS_DUPLICATED: 'bool',
    COLUMN.REGISTRY_TIME: 'datetime64[ns]',
    COLUMN.IS_CORRECTION: 'bool',
    COLUMN.USER_AND_DATE_INDEX: 'string[python]',
    COLUMN.COUNT: 'uint64',
    COLUMN.WEEKDAY: 'category',
    COLUMN.START_SCHEDULE: 'timedelta64[ns]',
    COLUMN.END_SCHEDULE: 'timedelta64[ns]',
    COLUMN.START_OFFSET: 'timedelta64[ns]',
    COLUMN.END_OFFSET: 'timedelta64[ns]',
    COLUMN.ALLOWED_START: 'datetime64[ns]',
    COLUMN.ALLOWED_END: 'datetime64[ns]',
    COLUMN.LATE_TIME: 'timedelta64[ns]',
    COLUMN.EARLY_TIME: 'timedelta64[ns]',
    COLUMN.TIME_IN_DELTA: 'timedelta64[ns]',
    COLUMN.EXCEEDING_LUNCH_TIME: 'timedelta64[ns]',
    COLUMN.PERMISSION_TYPE: 'category',
    COLUMN.PERMISSION_START: 'datetime64[ns]',
    COLUMN.PERMISSION_END: 'datetime64[ns]',
    COLUMN.HOLIDAY_NAME: 'string[python]',
    COLUMN.HOLIDAY_DATE: 'datetime64[ns]',
    COLUMN.IS_CLOSED_CORRECT: 'bool',
    COLUMN.IS_CURRENT_DAY_CHECKIN: 'bool',
    COLUMN.WORKED_DAYS: 'uint8',
}
"""
`dict[str, AstypeArg]` Tipos de dato asignados a las columnas de DataFrames.
"""

ORDERED_REGISTRY_TYPE = [
    REGISTRY_TYPE.NULL,
    REGISTRY_TYPE.UNDEFINED,
    REGISTRY_TYPE.CHECK_IN,
    REGISTRY_TYPE.BREAK_OUT,
    REGISTRY_TYPE.BREAK_IN,
    REGISTRY_TYPE.CHECK_OUT,
]
"""
`list[Literal]` Orden de tipos de registro.
"""

LUNCH_REGISTRY_TYPES = [
    REGISTRY_TYPE.BREAK_OUT,
    REGISTRY_TYPE.BREAK_IN,
]
"""
`list[Literal]` Tipos de registro de tiempo de comida.
"""

DAY_PERMISSIONS = [
    PERMISSION_NAME.SICK_GENERAL,
    PERMISSION_NAME.WORK_RISK,
    PERMISSION_NAME.MATERNITY,
    PERMISSION_NAME.UNJUSTIFIED_ABSENCE,
    PERMISSION_NAME.UNPAID_EXTRA_ABSENCE,
    PERMISSION_NAME.HOLIDAY_ABSENCE,
    PERMISSION_NAME.HOLIDAY_COMPENSATION,
]
"""
`list[Literal]` Permisos por días.
"""

TIME_PERMISSIONS = [
    PERMISSION_NAME.HOURS_PERMISSION,
    PERMISSION_NAME.OVERTIME,
    PERMISSION_NAME.MEAL_BREAK_MISSING,
    PERMISSION_NAME.MEAL_BREAK_COMPENSATION,
]
"""
`list[Literal]` Permisos por horas.
"""

PERMISSION_TYPE_REASSIGNATION_NAMES = {
    INPUT.FORM.PERMISSIONS.LABEL.VACATION: PERMISSION_NAME.VACATION,
    INPUT.FORM.PERMISSIONS.LABEL.SICK_GENERAL: PERMISSION_NAME.SICK_GENERAL,
    INPUT.FORM.PERMISSIONS.LABEL.WORK_RISK: PERMISSION_NAME.WORK_RISK,
    INPUT.FORM.PERMISSIONS.LABEL.MATERNITY: PERMISSION_NAME.MATERNITY,
    INPUT.FORM.PERMISSIONS.LABEL.UNJUSTIFIED_ABSENCE: PERMISSION_NAME.UNJUSTIFIED_ABSENCE,
    INPUT.FORM.PERMISSIONS.LABEL.UNJUSTIFIED_ABSENCE_: PERMISSION_NAME.UNJUSTIFIED_ABSENCE,
    INPUT.FORM.PERMISSIONS.LABEL.UNPAID_EXTRA_ABSENCE: PERMISSION_NAME.UNPAID_EXTRA_ABSENCE,
    INPUT.FORM.PERMISSIONS.LABEL.HOLIDAY_ABSENCE: PERMISSION_NAME.HOLIDAY_ABSENCE,
    INPUT.FORM.PERMISSIONS.LABEL.HOLIDAY_COMPENSATION: PERMISSION_NAME.HOLIDAY_COMPENSATION,
    INPUT.FORM.PERMISSIONS.LABEL.HOURS_PERMISSION: PERMISSION_NAME.HOURS_PERMISSION,
    INPUT.FORM.PERMISSIONS.LABEL.OVERTIME: PERMISSION_NAME.OVERTIME,
    INPUT.FORM.PERMISSIONS.LABEL.MEAL_BREAK_MISSING: PERMISSION_NAME.MEAL_BREAK_MISSING,
    INPUT.FORM.PERMISSIONS.LABEL.MEAL_BREAK_COMPENSATION: PERMISSION_NAME.MEAL_BREAK_COMPENSATION,
    INPUT.FORM.PERMISSIONS.LABEL.HOLIDAY_ABSENCE_: PERMISSION_NAME.HOLIDAY_ABSENCE,
}
"""
`dict[str, str]` Mapeo de reasignación de nombres para tipos de permiso
provenientes de los datos entrantes.
"""

ATTENDANCE_JUSTIFICATIONS_REASSIGNATION_NAMES = {
    INPUT.FORM.PERMISSIONS.COLUMN.NAME: COLUMN.NAME,
    INPUT.FORM.PERMISSIONS.COLUMN.PERMISSION_TYPE: COLUMN.PERMISSION_TYPE,
    INPUT.FORM.PERMISSIONS.COLUMN.PERMISSION_START: COLUMN.PERMISSION_START,
    INPUT.FORM.PERMISSIONS.COLUMN.PERMISSION_END: COLUMN.PERMISSION_END,
}
"""
`dict[str, str]` Mapeo de reasignación de nombres de columna de datos de
incidencias.
"""

WAREHOUSE_RENAME = {
    DATA.IDS.WAREHOUSE.CSL: WAREHOUSE_NAME.CSL,
    DATA.IDS.WAREHOUSE.SJC: WAREHOUSE_NAME.SJC,
}
"""
Mapa de reasignación de nombres de almacenes provenientes de Odoo.
"""
