from pandas._typing import AstypeArg
from ..constants import (
    COLUMN,
    PERMISSION_NAME,
    REGISTRY_TYPE,
    VALIDATION,
    WAREHOUSE_NAME,
)
from ..settings import INPUT, DATA

ASSIGNED_DTYPES: dict[str, AstypeArg] = {
    COLUMN.ID: 'string[python]',
    COLUMN.USER_ID: 'uint16',
    COLUMN.NAME: 'category',
    COLUMN.DATE: 'datetime64[s]',
    COLUMN.TIME: 'timedelta64[ns]',
    COLUMN.REGISTRY_TYPE: 'category',
    COLUMN.DEVICE: 'category',
    COLUMN.PAY_FREQUENCY: 'category',
    COLUMN.IS_DUPLICATED: 'bool',
    COLUMN.REGISTRY_TIME: 'datetime64[ns]',
    COLUMN.IS_CORRECTION: 'bool',
    COLUMN.USER_AND_DATE_INDEX: 'string[python]',
    COLUMN.COUNT: 'uint64',
    COLUMN.WEEKDAY: 'category',
    COLUMN.START_SCHEDULE: 'timedelta64[ns]',
    COLUMN.END_SCHEDULE: 'timedelta64[ns]',
    COLUMN.START_OFFSET: 'timedelta64[ns]',
    COLUMN.END_OFFSET: 'timedelta64[ns]',
    COLUMN.ALLOWED_START: 'datetime64[ns]',
    COLUMN.ALLOWED_END: 'datetime64[ns]',
    COLUMN.LATE_TIME: 'timedelta64[ns]',
    COLUMN.EARLY_TIME: 'timedelta64[ns]',
    COLUMN.TIME_IN_DELTA: 'timedelta64[ns]',
    COLUMN.EXCEEDING_LUNCH_TIME: 'timedelta64[ns]',
    COLUMN.PERMISSION_TYPE: 'category',
    COLUMN.PERMISSION_START: 'datetime64[ns]',
    COLUMN.PERMISSION_END: 'datetime64[ns]',
    COLUMN.HOLIDAY_NAME: 'string[python]',
    COLUMN.HOLIDAY_DATE: 'datetime64[ns]',
    COLUMN.IS_CLOSED_CORRECT: 'bool',
    COLUMN.IS_CURRENT_DAY_CHECKIN: 'bool',
    COLUMN.SCHEMA: 'category',
    COLUMN.WAREHOUSE: 'category',
    COLUMN.WORKED_DAYS: 'uint8',
    COLUMN.NULL_BY_JUSTIFICATION: 'bool',
    COLUMN.HIRE_DATE: 'datetime64[s]',
    COLUMN.SALARY_BY_SCHEMA: 'float64',
    COLUMN.INITIAL_DATE_FOR_HOLIDAYS: 'datetime64[s]',
    COLUMN.AVAILABLE_HOLIDAYS: 'uint8',
    COLUMN.REMAINING_HOLIDAYS: 'uint8',
}
"""
`dict[str, AstypeArg]` Tipos de dato asignados a las columnas de DataFrames.
"""

ORDERED_REGISTRY_TYPE = [
    REGISTRY_TYPE.NULL,
    REGISTRY_TYPE.UNDEFINED,
    REGISTRY_TYPE.CHECK_IN,
    REGISTRY_TYPE.BREAK_OUT,
    REGISTRY_TYPE.BREAK_IN,
    REGISTRY_TYPE.CHECK_OUT,
]
"""
`list[Literal]` Orden de tipos de registro.
"""

LUNCH_REGISTRY_TYPES = [
    REGISTRY_TYPE.BREAK_OUT,
    REGISTRY_TYPE.BREAK_IN,
]
"""
`list[Literal]` Tipos de registro de tiempo de comida.
"""

DAY_PERMISSIONS = [
    PERMISSION_NAME.SICK_GENERAL,
    PERMISSION_NAME.WORK_RISK,
    PERMISSION_NAME.MATERNITY,
    PERMISSION_NAME.UNJUSTIFIED_ABSENCE,
    PERMISSION_NAME.UNPAID_EXTRA_ABSENCE,
    PERMISSION_NAME.HOLIDAY_ABSENCE,
    PERMISSION_NAME.HOLIDAY_COMPENSATION,
]
"""
`list[Literal]` Permisos por días.
"""

TIME_PERMISSIONS = [
    PERMISSION_NAME.HOURS_PERMISSION,
    PERMISSION_NAME.OVERTIME,
    PERMISSION_NAME.MEAL_BREAK_MISSING,
    PERMISSION_NAME.MEAL_BREAK_COMPENSATION,
]
"""
`list[Literal]` Permisos por horas.
"""

PERMISSION_TYPE_REASSIGNATION_NAMES = {
    INPUT.FORM.PERMISSIONS.LABEL.VACATION: PERMISSION_NAME.VACATION,
    INPUT.FORM.PERMISSIONS.LABEL.SICK_GENERAL: PERMISSION_NAME.SICK_GENERAL,
    INPUT.FORM.PERMISSIONS.LABEL.WORK_RISK: PERMISSION_NAME.WORK_RISK,
    INPUT.FORM.PERMISSIONS.LABEL.MATERNITY: PERMISSION_NAME.MATERNITY,
    INPUT.FORM.PERMISSIONS.LABEL.UNJUSTIFIED_ABSENCE: PERMISSION_NAME.UNJUSTIFIED_ABSENCE,
    INPUT.FORM.PERMISSIONS.LABEL.UNJUSTIFIED_ABSENCE_: PERMISSION_NAME.UNJUSTIFIED_ABSENCE,
    INPUT.FORM.PERMISSIONS.LABEL.UNPAID_EXTRA_ABSENCE: PERMISSION_NAME.UNPAID_EXTRA_ABSENCE,
    INPUT.FORM.PERMISSIONS.LABEL.HOLIDAY_ABSENCE: PERMISSION_NAME.HOLIDAY_ABSENCE,
    INPUT.FORM.PERMISSIONS.LABEL.HOLIDAY_COMPENSATION: PERMISSION_NAME.HOLIDAY_COMPENSATION,
    INPUT.FORM.PERMISSIONS.LABEL.HOURS_PERMISSION: PERMISSION_NAME.HOURS_PERMISSION,
    INPUT.FORM.PERMISSIONS.LABEL.OVERTIME: PERMISSION_NAME.OVERTIME,
    INPUT.FORM.PERMISSIONS.LABEL.MEAL_BREAK_MISSING: PERMISSION_NAME.MEAL_BREAK_MISSING,
    INPUT.FORM.PERMISSIONS.LABEL.MEAL_BREAK_COMPENSATION: PERMISSION_NAME.MEAL_BREAK_COMPENSATION,
    INPUT.FORM.PERMISSIONS.LABEL.HOLIDAY_ABSENCE_: PERMISSION_NAME.HOLIDAY_COMPENSATION,
}
"""
`dict[str, str]` Mapeo de reasignación de nombres para tipos de permiso
provenientes de los datos entrantes.
"""

ATTENDANCE_JUSTIFICATIONS_REASSIGNATION_NAMES = {
    INPUT.FORM.PERMISSIONS.COLUMN.NAME: COLUMN.NAME,
    INPUT.FORM.PERMISSIONS.COLUMN.PERMISSION_TYPE: COLUMN.PERMISSION_TYPE,
    INPUT.FORM.PERMISSIONS.COLUMN.PERMISSION_START: COLUMN.PERMISSION_START,
    INPUT.FORM.PERMISSIONS.COLUMN.PERMISSION_END: COLUMN.PERMISSION_END,
}
"""
`dict[str, str]` Mapeo de reasignación de nombres de columna de datos de
incidencias.
"""

WAREHOUSE_RENAME = {
    DATA.IDS.WAREHOUSE.CSL: WAREHOUSE_NAME.CSL,
    DATA.IDS.WAREHOUSE.SJC: WAREHOUSE_NAME.SJC,
}
"""
Mapa de reasignación de nombres de almacenes provenientes de Odoo.
"""

USERS_DATA_REASSIGNATION_NAMES = {
    INPUT.FORM.USERS_DATA.COLUMN.USER_ID: COLUMN.USER_ID,
    INPUT.FORM.USERS_DATA.COLUMN.HIRE_DATE: COLUMN.HIRE_DATE,
    INPUT.FORM.USERS_DATA.COLUMN.SALARY_BY_SCHEMA: COLUMN.SALARY_BY_SCHEMA,
}

COLUMN_LABELS: dict[str, str] = {
    COLUMN.ID: 'ID en base de datos',
    COLUMN.USER_ID: 'ID de usuario',
    COLUMN.NAME: 'Nombre',
    COLUMN.DATE: 'Fecha',
    COLUMN.TIME: 'Hora',
    COLUMN.REGISTRY_TYPE: 'Estatus',
    COLUMN.DEVICE: 'Dispositivo',
    COLUMN.PAY_FREQUENCY: 'Frecuencia de pago',
    COLUMN.IS_DUPLICATED: 'Duplicado',
    COLUMN.REGISTRY_TIME: 'Fecha y hora',
    COLUMN.IS_CORRECTION: 'Corrección',
    COLUMN.USER_AND_DATE_INDEX: 'Índice de usuario + fecha',
    COLUMN.COUNT: 'Conteo',
    COLUMN.WEEKDAY: 'Día de la semana',
    COLUMN.START_SCHEDULE: 'Inicio de horario',
    COLUMN.END_SCHEDULE: 'Fin de horario',
    COLUMN.START_OFFSET: 'Desfase de inicio',
    COLUMN.END_OFFSET: 'Desfase de fin',
    COLUMN.ALLOWED_START: 'Entrada permitida',
    COLUMN.ALLOWED_END: 'Salida permitida',
    COLUMN.LATE_TIME: 'Min retardos',
    COLUMN.EARLY_TIME: 'Salida anticipada',
    COLUMN.TIME_IN_DELTA: 'Delta en tiempo',
    COLUMN.EXCEEDING_LUNCH_TIME: 'Min extra comida',
    COLUMN.PERMISSION_TYPE: 'Tipo de permiso',
    COLUMN.PERMISSION_START: 'Inicio de permiso',
    COLUMN.PERMISSION_END: 'Fin de permiso',
    COLUMN.HOLIDAY_NAME: 'Nombre de día festivo',
    COLUMN.HOLIDAY_DATE: 'Fecha de día festivo',
    COLUMN.WAREHOUSE: 'Almacén',
    COLUMN.SCHEMA: 'Esquema',
    COLUMN.VACATION_DAYS_COUNT: 'Días de vacaciones',
    COLUMN.AVAILABLE_HOLIDAYS: 'Días festivos disponibles',
    COLUMN.REMAINING_HOLIDAYS: 'Días festivos restantes',
    COLUMN.IS_CLOSED_CORRECT: 'Es día cerrado correcto',
    COLUMN.IS_CURRENT_DAY_CHECKIN: 'Es entrada de día en curso',
    COLUMN.WORKED_DAYS: 'Días laborados',
    COLUMN.NULL_BY_JUSTIFICATION: 'Anulado por vacaciones y horas extra',
    COLUMN.HIRE_DATE: 'Fecha de ingreso',
    COLUMN.SALARY_BY_SCHEMA: 'Salario',
    COLUMN.INITIAL_DATE_FOR_HOLIDAYS: 'Fecha de inicio para días festivos',

    VALIDATION.COMPLETE: 'Día completo',
    VALIDATION.BREAK_PAIRS: 'Pares en comida',
    VALIDATION.UNIQUE_START_AND_END: 'Un solo inicio y fin de jornada',
    VALIDATION.IS_LATE_START: 'Es entrada tardía',
    VALIDATION.IS_EARLY_END: 'Es salida anticipada',

    PERMISSION_NAME.VACATION: 'Vacaciones',
    PERMISSION_NAME.SICK_GENERAL: 'Enfermedad general',
    PERMISSION_NAME.WORK_RISK: 'Riesgo de trabajo',
    PERMISSION_NAME.MATERNITY: 'Maternidad',
    PERMISSION_NAME.UNJUSTIFIED_ABSENCE: 'Falta',
    PERMISSION_NAME.UNPAID_EXTRA_ABSENCE: 'Falta (sin bono, sin pago)',
    PERMISSION_NAME.HOLIDAY_ABSENCE: 'Festivo',
    PERMISSION_NAME.HOLIDAY_COMPENSATION: 'Compensación festivo',
    PERMISSION_NAME.HOURS_PERMISSION: 'Permiso de horas',
    PERMISSION_NAME.OVERTIME: 'Horas extra',
    PERMISSION_NAME.MEAL_BREAK_MISSING: 'Sin hora de comida',
    PERMISSION_NAME.MEAL_BREAK_COMPENSATION: 'Compensación por hora de comida',
}
